Tensor gym

Create tensors from Python lists/NumPy, control dtype & device (CPU/GPU).

Do reshaping (view, reshape, permute), broadcasting ops, indexing/slicing, and reductions.

Show deterministic vs nondeterministic random seeds (torch.manual_seed).

Deliverable: a short notebook demonstrating each op with a one-line explanation.

In [2]:
import torch
import numpy as np

In [7]:
print(torch.cuda.is_available())

False


In [8]:
print(torch.backends.mps.is_available())

True


In [9]:
# list to tensor
l1 = [1,2,3]
t1 = torch.tensor(l1)

# numpy array to tensor
l2 = np.array([1,2,3])
t2 = torch.from_numpy(l2)

# default tensor dtype is float32
# can explicity reassign using dtype method
l3 = [1,2,3]
t3 = torch.tensor(l3, dtype=torch.float64)

# decide where tensor should live (cpu is by default, if you use cuda, ir reroutes to gpu)
t3 = torch.tensor(l3, device="cpu")
t3 = torch.tensor(l3, device="mps")

# call the whole thing now

In [20]:
t4 = torch.tensor(l3, dtype=torch.float32, device="mps")

In [26]:
t4 = torch.tensor(l2, dtype=torch.float32, device="mps")

In [35]:
t5 = torch.tensor(l2, dtype=torch.float32, device="mps")

In [36]:
print(t5+1)
print(t5*2)
print(torch.sqrt(t5))
print(t5.dtype)
print(t5.device)

tensor([2., 3., 4.], device='mps:0')
tensor([2., 4., 6.], device='mps:0')
tensor([1.0000, 1.4142, 1.7321], device='mps:0')
torch.float32
mps:0
